// Power BI: create a text parameter named OCI_FOCUS_PAR_URL and paste the
// powerbi_url value printed by delivery/focus_to_sharepoint.py.
// The PAR points to powerbi/oci_focus_previous_week.csv in OCI Object Storage.
let
    Source = Web.Contents(OCI_FOCUS_PAR_URL),
    Csv = Csv.Document(Source, [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
    Promoted = Table.PromoteHeaders(Csv, [PromoteAllScalars = true]),
    Typed = Table.TransformColumnTypes(Promoted, {
        {"BilledCost", Currency.Type}, {"EffectiveCost", Currency.Type},
        {"ListCost", Currency.Type}, {"ContractedCost", Currency.Type},
        {"BilledQuantity", type number}, {"ChargePeriodStart", type datetimezone},
        {"ChargePeriodEnd", type datetimezone}, {"BillingPeriodStart", type datetimezone},
        {"BillingPeriodEnd", type datetimezone}, {"ResourceId", type text}
    }, "en-US"),
    // Do not filter correction rows. Reconcile lineItem/IsCorrection and
    // lineItem/BackReference in measures where a corrected net view is needed.
    Result = Typed
in
    Result
